cask_args appdir: "/Applications"

brew "git"
brew "ripgrep"
brew "vim"
brew "zsh"
brew "zsh-completions"
brew "docker"
brew "pyenv"
brew "rbenv"
brew "go"
brew "elixir"
brew "sbt"
brew "peco"
brew "usbmuxd"
brew "libimobiledevice"
brew "ideviceinstaller"
brew "ios-deploy"
brew "cocoapods"

tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "railwaycat/emacsmacport"
tap "AdoptOpenJDK/openjdk"

cask "google-chrome"
cask "slack"
cask "iterm2"
cask "jetbrains-toolbox"
cask "docker"
cask "postman"
cask "karabiner-elements"
cask "alfred"
cask "zeplin"
cask "abstract"
cask "emacs-mac-spacemacs-icon"
cask "google-japanese-ime"
cask "hyperswitch"
cask "scroll-reverser"
cask "station"
cask "adoptopenjdk8"
cask "1password"
